#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pcsc-tools
Version  : 1.4.24
Release  : 2
URL      : http://ludovic.rousseau.free.fr/softwares/pcsc-tools/pcsc-tools-1.4.24.tar.gz
Source0  : http://ludovic.rousseau.free.fr/softwares/pcsc-tools/pcsc-tools-1.4.24.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: pcsc-tools-bin
Requires: pcsc-tools-doc
Requires: pcsc-tools-data
BuildRequires : pkgconfig(libpcsclite)
Patch1: no-best.patch

%description
Some tools to be used with smart cards and PC/SC
================================================

%package bin
Summary: bin components for the pcsc-tools package.
Group: Binaries
Requires: pcsc-tools-data

%description bin
bin components for the pcsc-tools package.


%package data
Summary: data components for the pcsc-tools package.
Group: Data

%description data
data components for the pcsc-tools package.


%package doc
Summary: doc components for the pcsc-tools package.
Group: Documentation

%description doc
doc components for the pcsc-tools package.


%prep
%setup -q -n pcsc-tools-1.4.24
%patch1 -p1

%build
make V=1  %{?_smp_mflags}

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ATR_analysis
/usr/bin/gscriptor
/usr/bin/pcsc_scan
/usr/bin/scriptor

%files data
%defattr(-,root,root,-)
/usr/share/pcsc/smartcard_list.txt

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
